const express = require("express");
const { error404, error500 } = require("../controllers/errors");
const { signIn, signUp } = require("../controllers/auth");
const { join } = require("path");
const router = express.Router();
router.post("/signup", signUp);
// router.post("/singin", signIn);
router.use(error404);
router.use(error500);
module.exports = router;
